import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

const faqs = [
    {
        question: 'Is the content generated by EssayFlow plagiarism-free?',
        answer: 'Yes, our AI generates unique content for every prompt. However, we always recommend using our built-in plagiarism checker and citing your sources properly.'
    },
    {
        question: 'Can I use EssayFlow for any academic level?',
        answer: 'Absolutely! You can customize the complexity and tone of the output to match High School, Undergraduate, or Post-Graduate levels.'
    },
    {
        question: 'Does it support other languages?',
        answer: 'Currently, EssayFlow is optimized for English, but we are working on adding support for Spanish, French, and German in the near future.'
    },
    {
        question: 'How does the free trial work?',
        answer: 'You get full access to the Pro plan features for 14 days. No credit card is required to start. If you don\'t upgrade, your account automatically switches to the Free plan.'
    },
    {
        question: 'Can I cancel my subscription anytime?',
        answer: 'Yes, you can cancel your subscription at any time from your account settings. You will retain access until the end of your billing period.'
    }
];

const FAQ = () => {
    const [openIndex, setOpenIndex] = useState(null);

    return (
        <section id="faq" className="py-20 bg-gray-50">
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-16">
                    <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-4">
                        Frequently Asked Questions
                    </h2>
                    <p className="text-lg text-gray-600">
                        Have questions? We're here to help.
                    </p>
                </div>

                <div className="space-y-4">
                    {faqs.map((faq, index) => (
                        <div key={index} className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                            <button
                                className="w-full px-6 py-4 text-left flex justify-between items-center focus:outline-none"
                                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                            >
                                <span className="text-lg font-medium text-gray-900">{faq.question}</span>
                                {openIndex === index ? (
                                    <ChevronUp className="h-5 w-5 text-indigo-600" />
                                ) : (
                                    <ChevronDown className="h-5 w-5 text-gray-400" />
                                )}
                            </button>
                            {openIndex === index && (
                                <div className="px-6 pb-4 text-gray-600 leading-relaxed animate-fadeIn">
                                    {faq.answer}
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default FAQ;
